name: zabihtk
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+15


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations:
  intl_translation: ^0.17.7
  provider: ^3.2.0
  shared_preferences: ^0.5.6
  http: ^0.12.2
  # device_preview: ^0.2.6
  flutter_launcher_icons: ^0.7.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  validators: ^2.0.0
  toast: ^0.1.5
  flutter_offline: ^0.2.4+1
  flutter_spinkit: ^4.1.2
  dio: ^3.0.9
  dots_indicator: ^1.1.0
  url_launcher: ^5.4.1
  flutter_html: ^0.11.0
  smooth_star_rating: ^1.0.3
  location: ^3.0.0
  geolocator: ^5.3.1
  google_maps_flutter: ^0.5.27+2
  carousel_slider: ^1.3.1
  image_picker: ^0.6.6+5
  path: ^1.6.2
  firebase_messaging: ^6.0.9
  flutter_local_notifications:






dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
#  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/app_icon.png"
  image_path_ios: "assets/images/app_icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splash.png
    - assets/images/cart.png
    - assets/images/profile.png
    - assets/images/profile1.png
    - assets/images/requests.png
    - assets/images/home.png
    - assets/images/search.png
    - assets/images/toplogo.png
    - assets/images/tobbg.png
    - assets/images/arabic.png
    - assets/images/english.png
    - assets/images/about.png
    - assets/images/bank.png
    - assets/images/edit.png
    - assets/images/logout.png
    - assets/images/opinion.png
    - assets/images/lang.png
    - assets/images/login.png
    - assets/images/back_ar.png
    - assets/images/back_en.png
    - assets/images/logo.png
    - assets/images/key.png
    - assets/images/phone.png
    - assets/images/minus.png
    - assets/images/plus.png
    - assets/images/stomach.png
    - assets/images/box.png
    - assets/images/sheep.png
    - assets/images/crop.png
    - assets/images/cursor.png
    - assets/images/poprate.png
    - assets/images/email.png
    - assets/images/city.png
    - assets/images/down.png
    - assets/images/popphone.png
    - assets/images/full_edit.png
    - assets/images/contact.png
    - assets/images/facebook.png
    - assets/images/linkedin.png
    - assets/images/twitter.png
    - assets/images/instagram.png
    - assets/images/delivery.png
    - assets/images/delivery1.png
    - assets/images/logoutwh.png
    - assets/images/callfull.png
    - assets/images/alert.png
    - assets/images/notification.png
    - assets/images/location.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NeoSans
      fonts:
        - asset: assets/fonts/Tajawal-Regular.TTF
          weight: 400
        - asset: assets/fonts/Tajawal-Bold.TTF
          weight: 700
        - asset: assets/fonts/Tajawal-Medium.TTF
          weight: 500


    - family: HelveticaNeueW23forSKY
      fonts:
        - asset: assets/fonts/Tajawal-Regular.TTF


    - family: Helvetica
      fonts:
        - asset: assets/fonts/Tajawal-Bold.TTF

#
#
#    - family: phone
#      fonts:
#        - asset: assets/fonts/icons/phone.ttf
#
#
#    - family: group
#      fonts:
#        - asset: assets/fonts/icons/group.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

